name: Build Gradle Project
run-name: Build Gradle Project
on: [push]
jobs:
    build-gradle-project:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Java
          uses: actions/setup-java@v3
          with:
            distribution: zulu
            java-version: 17

        - name: Setup Gradle
          uses: gradle/gradle-build-action@v2
          with:
            gradle-version: 8.3

        - name: Build
          run: ./gradlew build --no-daemon --no-configuration-cache
